# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/myblog',
                'doc_host': 'https://prashanthnayak.github.io',
                'git_url': 'https://github.com/prashanthnayak/myblog',
                'lib_path': 'myblog'},
  'syms': {'myblog.core': {'myblog.core.foo': ('core.html#foo', 'myblog/core.py')}}}
